codecov:
  notify:
    require_ci_to_pass: yes

comment: off

coverage:
  precision: 2
  round: up
  range: "70...100"
  status:
    patch:
      default:
        threshold: "10%"
        only_pulls: true
    project:
      azure:
        paths: "tools/c7n_azure"
        threshold: "1%"
      gcp:
        paths: "tools/c7n_gcp"
        threshold: "1%"
      # aws is weaved throughout core atm can't easily call it out separately
      mailer:
        paths: "tools/c7n_mailer"
        threshold: "2%"
      custodian:
      # one of the tests is slightly variable coverage due to concurrency (0.01)
        threshold: "0.05%"
        paths:
          - "!tools"
      default: off
